#Example submission script for lab1
#PBS -N lab1_hj_gpu
#PBS -l nodes=1:ppn=8:core40:gpus=1:teslav100:exclusive_process
#PBS -l walltime=00:20:00
#PBS -q coc-ice-gpu
#PBS -j oe
#PBS -o job.$PBS_JOBID.out
#PBS -e job.$PBS_JOBID.err
#PBS -n

#Setup Environment
cd $PBS_O_WORKDIR
source pace_env.sh

make clean metrics IMPL=hj
./metrics -t 50 -n 10000000 -o results_hj_cuda.json

exit 0
